import { set, get } from "./functions.js";
export const products = [
{
"productType" : ["nft", "non-clothing", "all"],
"productTag" : "item1",
"name" :"Elle mugshot",
"image" :"./images/Elle.JPEG",
"imageCount" : 4,
"price": 7.00,
"colour" : ["one colour", "red", "yellow", "blue", "black"],
"size" : ["one size", "large", "medium", "small"],
"description": `A selection of nft's each perfectly composed and crafted over the course of two years at AUEA,
 each moment captures a specific point in time. This specific selection features Elle and her friends the
 first was taken at AUEA, the second at the Asian food court, the third back at AUEA on the final day of
 school at the final photo was taken during a groupcall`,
"deliveryDetails": "get it when you want",
"additionalInfo": "Bestseller"
},
{
"productType" : ["nft", "non-clothing", "all"],
"productTag" : "item2",
"name":"Monil mugshot",
"image" :"./images/Monil.JPEG",
"imageCount" : 3,
"price": 6.00,
"colour" : ["one colour", "red", "yellow"],
"size" : ["one size", "large", "medium", "small"],
"description" : `A selection of nft's each perfectly composed and crafted over the course of two years at AUEA,
 each moment captures a specific point in time`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["trousers", "clothing", "all"],
"productTag" : "item3",
"name" :"Erin mugshot",
"image" :"./images/Erin.JPG",
"imageCount" : 5,
"price": 7.00,
"colour" : ["one colour", "red", "yellow", "green"],
"size" : ["one size", "large", "medium", "small"],
"description" : `A selection of nft's each perfectly composed and crafted over the course of two years at AUEA,
 each moment captures a specific point in time`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["shirt", "clothing", "all"],
"productTag" : "item4",
"name":"Sam mugshot",
"image" :"./images/Sam.JPG",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `A selection of nft's each perfectly composed and crafted over the course of two years at AUEA,
 each moment captures a specific point in time`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["belt", "clothing", "all"],
"productTag" : "item5",
"name":"Zain mugshot",
"image" :"./images/Sam.JPG",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `A selection of nft's each un-perfectly composed and crafted over the course of two years at AUEA,
 each moment captures a specific point in time`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["belt", "clothing", "all"],
"productTag" : "item6",
"name":"A nice cup of tea",
"image" :"./images/Sam.JPG",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `take a break, perhaps have some tea (this item is apparently a belt)`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["belt", "clothing", "all"],
"productTag" : "item7",
"name":"Keep calm and carry on",
"image" :"./images/Sam.JPG",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `take a break, (this item is apparently a belt)`,
"deliveryDetails": "get it when you want",
}
]
