import { set, get } from "./functions.js";
export const products = [
{
"productType" : ["nft", "non-clothing", "men", "all"], // first type is actual item eg: "shirt" second is 
"productTag" : "item1",                         //clothing or non clothing, third is gender, fourth doesnt matter
"name" :"Elle mugshot",  // recommend keeping the name 20 (73) characters long (27 is theoretical best but when combi-
"imageCount" : 4,        // ned with name it gets too long in the universalDisplay)
"price": 7.00,           
"colour" : ["one colour", "red", "yellow", "blue", "black"],// the last cell is smaller than the others (bug)
"size" : ["one size", "large", "medium", "small"],
"description": `A selection of nft's each perfectly composed and crafted over the course of two years at AUEA,
 each moment captures a specific point in time. This specific selection features Elle and her friends the
 first was taken at AUEA, the second at the Asian food court, the third back at AUEA on the final day of
 school at the final photo was taken during a groupcall`,// need to be jpeg 's (just rename them in the image folder)
"deliveryDetails": "get it when you want", // there is a recommended size for the photos,
"additionalInfo": "Bestseller"//i suggest using standard landscape and portrait sizes, make sure they fill imagecolumn2
},
{
"productType" : ["nft", "non-clothing", "unisex", "all"],
"productTag" : "item2",
"name":"Monil mugshot",
"imageCount" : 3,
"price": 6.00,
"colour" : ["one colour", "red", "yellow"],
"size" : ["one size", "large", "medium", "small"],
"description" : `A selection of nft's each perfectly composed and crafted over the course of two years at AUEA,
 each moment captures a specific point in time`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["trousers", "clothing","unisex", "all"],
"productTag" : "item3",
"name" :"Erin mugshot",
"imageCount" : 5,
"price": 7.00,
"colour" : ["one colour", "red", "yellow", "green"],
"size" : ["one size", "large", "medium", "small"],
"description" : `A selection of nft's each perfectly composed and crafted over the course of two years at AUEA,
 each moment captures a specific point in time`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["shirt", "clothing", "all"],
"productTag" : "item4",
"name":"Sam mugshot",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `A selection of nft's each perfectly composed and crafted over the course of two years at AUEA,
 each moment captures a specific point in time`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["belt", "clothing", "all"],
"productTag" : "item5",
"name":"Zain mugshot",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `A selection of nft's each un-perfectly composed and crafted over the course of two years at AUEA,
 each moment captures a specific point in time`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["belt", "clothing", "all"],
"productTag" : "item6",
"name":"Cup of tea",
"imageCount" : 3,
"price": 6.00,
"colour" : ["one colour", "red", "blue"],  // something wierd going on here
"size" : ["one size"],
"description" : `take a break, perhaps have some tea (this item is apparently a belt)`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["belt", "clothing", "all"],
"productTag" : "item7",
"name":"Keep calm and carry on",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour", "red", "blue"], 
"size" : ["one size"],
"description" : `take a break, (this item is apparently a belt)`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["socks", "clothing", "men", "all"],
"productTag" : "item8",
"name":"inspirational message",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour", "red", "blue"],
"size" : ["one size"],
"description" : `take a break, (this item is apparently a belt)`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["hoodie", "clothing", "unisex", "all"],
"productTag" : "item9",
"name":"Rolls Royce Boatail",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `take a break, (this item is apparently a belt)`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["belt", "clothing", "men", "all"],
"productTag" : "item10",
"name":"name is 27 characters",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `take a break, (this item is apparently a belt)`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["watch", "clothing", "unisex", "all"],
"productTag" : "item11",
"name":" if you have an axe, ",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `take a break, (this item is apparently a belt)`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["belt", "clothing", "unisex", "all"],
"productTag" : "item12",
"name":" the twelfth item ",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `take a break, (this item is apparently a belt)`,
"deliveryDetails": "get it when you want",
},
{
"productType" : ["belt", "clothing", "unisex", "all"],
"productTag" : "item13",
"name":"if u have an axe, & replace le handle 3 times & head 5 times cest le same?",
"imageCount" : 4,
"price": 6.00,
"colour" : ["one colour"],
"size" : ["one size"],
"description" : `take a break, (this item is apparently a belt)`,
"deliveryDetails": "get it when you want",
},
]
